### PR TITLE
feat: Implement o200k_base encoding and support gpt-4o

### PR DESCRIPTION
**Pull request by chatanywhere**
Implement o200k_base encoding and support gpt-4o

### CODE REVIEW

**Comment by fernando-arellano** [comment]
Hello @tox-p  thanks for all the support on maintaining this repo. Is there anything we can do to help you with this PR? we're relying on this library in our project and righ now we're looking to start using gpt4o but it seems the library doesn't have support yet for gpt4 o. please let us know if there is something we can do to help with this.

**Comment by jcrupi** [comment]
Checking in on this approval

**Comment by mkemmerz** [comment]
@tox-p Sorry to annoy you directly but any plan to review this PR?

**Comment by keyurgolani7878** [comment]
Hey, @tox-p Can you provide update on when are you planning to review the PR? I need gpt-4o encoding ASAP. Thanks!

**Comment by Grogdunn** [comment]
meanwhile :zipper_mouth_face: 
```
<dependency>
    <groupId>net.optionfactory</groupId>
    <artifactId>jtokkit</artifactId>
    <version>1.1.1</version>
</dependency>
```

**Comment by keyurgolani7878** [comment]
> net.optionfactory

 I can't find this on maven central? Can you help me?

**Comment by keyurgolani7878** [comment]
> meanwhile 🤐
> 
> ```
> <dependency>
>     <groupId>net.optionfactory</groupId>
>     <artifactId>jtokkit</artifactId>
>     <version>1.1.1</version>
> </dependency>
> ```



> meanwhile 🤐
> 
> ```
> <dependency>
>     <groupId>net.optionfactory</groupId>
>     <artifactId>jtokkit</artifactId>
>     <version>1.1.1</version>
> </dependency>
> ```

I can't find this on maven central. Can you help me?

**Comment by Grogdunn** [comment]
> > meanwhile 🤐
> > ```
> > <dependency>
> >     <groupId>net.optionfactory</groupId>
> >     <artifactId>jtokkit</artifactId>
> >     <version>1.1.1</version>
> > </dependency>
> > ```
> 
> I can't find this on maven central. Can you help me?

Strange, I've released this morning and I see in central portal: https://central.sonatype.com/artifact/net.optionfactory/jtokkit

**Comment by mkemmerz** [comment]
> > > meanwhile 🤐
> > > ```
> > > <dependency>
> > >     <groupId>net.optionfactory</groupId>
> > >     <artifactId>jtokkit</artifactId>
> > >     <version>1.1.1</version>
> > > </dependency>
> > > ```
> > 
> > 
> > I can't find this on maven central. Can you help me?
> 
> Strange, I've released this morning and I see in central portal: https://central.sonatype.com/artifact/net.optionfactory/jtokkit

Not sure what dependency that is but not the one from this Github repo, this is the correct maven repo: https://mvnrepository.com/artifact/com.knuddels/jtokkit

**Comment by Grogdunn** [comment]
@mkemmerz of course that dependency has different groupId. It came from a fork with merged support for GPT-4o and GPT-4-turbo models. Nothing "strange", I've need of this functionality for some customers, so I've published myself. Here the fork https://github.com/optionfactory/jtokkit and thanks for the peole who made the PR.

**Comment by joesh36** [comment]
Any progress made to merge it to the main repo?

**Comment by joesh36** [comment]
Hey, @tox-p there is a plan to review this PR soon? we really need this encoding. 
Thanks

**Comment by mkemmerz** [comment]
Thanks 👍

**Pull request merged**
